# Generated by Django 6.0.8 on 2026-08-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='answer',
            field=models.TextField(blank=True, default=''),
        ),
    ]
