# Generated by Django 6.0.8 on 2026-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_node_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
