# Generated by Django 6.0.8 on 2026-08-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='life',
            field=models.IntegerField(default=5),
        ),
    ]
