# Generated by Django 6.0.8 on 2026-08-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_team_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='alt_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='node',
            name='alt_next_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_next_node', to='users.node'),
        ),
    ]
