# Generated by Django 6.0.8 on 2026-08-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_node_alt_answer_node_alt_next_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='attack',
            field=models.IntegerField(default=0),
        ),
    ]
