# Generated by Django 6.0.8 on 2026-08-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_node_attack_team_attack'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='life',
            field=models.IntegerField(default=0),
        ),
    ]
