# Generated by Django 6.0.8 on 2026-08-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_node_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='clue',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
