# Generated by Django 6.0.8 on 2026-08-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_gamehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='effects',
            field=models.CharField(choices=[('JUNCTION', 'Junction'), ('UNLOCKED', 'Unlocked')], default='UNLOCKED', max_length=20),
        ),
    ]
