# Generated by Django 6.0.8 on 2026-08-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_node_effects'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_nearest',
            field=models.BooleanField(default=False),
        ),
    ]
