# Generated by Django 6.0.8 on 2026-08-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_team_is_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='parents', to='users.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
