# Generated by Django 6.0.8 on 2026-08-21 11:27

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_team_is_won'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamnode',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamnode',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamnode',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamnode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.teamnode'),
        ),
        migrations.AddField(
            model_name='teamnode',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamnode',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teamnode',
            unique_together={('team', 'node', 'parent')},
        ),
    ]
