# Generated by Django 6.0.8 on 2026-08-31 06:50

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_teamnode_unique_together_teamnode_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='alt_next_node',
        ),
        migrations.RemoveField(
            model_name='node',
            name='next_node',
        ),
        migrations.AddField(
            model_name='node',
            name='alt_child',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_parent', to='users.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='alt_parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternative_child', to='users.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='users.node'),
        ),
        migrations.AddField(
            model_name='node',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
