# Generated by Django 6.0.8 on 2026-09-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_node_alt_next_node_remove_node_next_node_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamnode',
            options={'ordering': ['created_at']},
        ),
    ]
