# Generated by Django 6.0.8 on 2026-09-07 04:43

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_teamnode_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='users.node'),
        ),
        migrations.AlterField(
            model_name='teamnode',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='users.teamnode'),
        ),
    ]
