# Generated by Django 6.0.8 on 2026-09-08 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_node_parent_alter_teamnode_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='alt_child',
        ),
    ]
