# Generated by Django 6.0.8 on 2026-09-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_node_alt_child'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='position',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
