# Generated by Django 6.0.8 on 2026-10-01 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('users', '0020_node_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='alt_parent',
        ),
        migrations.RemoveField(
            model_name='node',
            name='parent',
        ),
        migrations.AlterField(
            model_name='team',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.node'),
        ),
        migrations.RemoveField(
            model_name='teamnode',
            name='node',
        ),
        migrations.AlterField(
            model_name='team',
            name='last_checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_checkpoint', to='game.node'),
        ),
        migrations.AlterField(
            model_name='team',
            name='current_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_node', to='game.node'),
        ),
        migrations.AlterUniqueTogether(
            name='teamnode',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teamnode',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='teamnode',
            name='team',
        ),
        migrations.DeleteModel(
            name='GameHistory',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='TeamNode',
        ),
    ]
